### ISSUE TITLE
Heap compaction is not working

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#1354]
### Target name(s)

ALL

### Firmware version

N/A

### Was working before? On which version?

Nope

### Description

When using any application that make the GC to kick in and subsequently require heap compaction cause hard fault on the device (on the virtual device it causes memory access exception).

```[tasklist]
### Tasks
- [x] Add Profiler tool to analyse object creation/deletion/heap management
- [x] Improve debug output in interpreter to provide more/better details on GC and heap compaction
- [x] Find and fix root cause
```

**Comment by josesimoes** [comment]
cc @sky9mike @MateuszKlatecki

**Comment by josesimoes** [comment]
From new unit tests added, long run tests and test applications stressing the GC the issue with GC and heap compaction has been fixed. For details on various fixes and improvements made, please check the individual PRs listed above.
