### ISSUE TITLE
Replace tinyprintf implementation

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#693]
### Details about Problem

**nanoFramework area:**  interpreter

### Description
Need to replace current implementation of printf.
Went back to an old potential candidate from [Kustaa Nyholm](http://www.sparetimelabs.com/tinyprintf/tinyprintf.php).
Reached out to him about the licensing and it's now available as MIT, so we are good to go.

Attached the ZIP file with the sources.
[mit-bsd-lgpl-printf.zip](https://github.com/nanoframework/Home/files/5943709/mit-bsd-lgpl-printf.zip)

### Tasks

- [ ] Replace the current code in `src\CLR\Helpers\TinyPrintf\printf.c` and `src\CLR\Helpers\TinyPrintf\printf.h`.
- [ ] Update copyright headers to match the project ones.
- [ ] Update calls from targets as required.

**Comment by josesimoes** [comment]
@SandorDobos would you be interested in taking care of this?

**Comment by SandorDobos** [comment]
Kustaa's version lacks some features:
- there is no snprintf
- there is no vsnprintf
- there are no doubles
Should we reimplement these?

**Comment by josesimoes** [comment]
> Should we reimplement these?

Considering that:
1. What we have is also needing fixes.
2. We now know the author and can credit it for and reach out for comments and/or contribute back with improvements.
3. Doesn't seem too daunting to add those.

I would say yes. Thoughts?

**Comment by SandorDobos** [comment]
Just for test I migrated this one: https://github.com/charlesnicholson/nanoprintf
Very clean implementation. Avoids sprintf and has only sn variants. Much safer :)

But this printf-thing is still one of the cubes composing the Big ToString quest in nf :)
Output still needs tweaking, see #679.

I am going to fix this if I may use nanoprintf or the TinyPrintf code we already have.
I wouldn't dive into Kustaa's implementation if possible.

**Comment by josesimoes** [comment]
No problem with using that. The license is OK for the project.
Feel free to proceed.

**Comment by josesimoes** [comment]
@SandorDobos just checking if you're tackling this or not. Thanks!

**Comment by SandorDobos** [comment]
Yes!

Dobos Sanyi

2021. február 12. 18:04:23 CET, "José Simões" <notifications@github.com> írta:
